spring:

  # Active profile
  profiles.active: dev
  
  # JSON serialization settings
  jackson:
    default-property-inclusion: NON_NULL
    
    serialization:
      write-null-map-values: false 
      
    deserialization:
      accept-single-value-as-array: true
      
  cloud:
    stream:
      bindings:
        user-input-channel:
          destination: user-topic
          group: ${spring.application.name}
          content-type: application/json
        user-output-channel:
          destination: user-topic
          group: ${spring.application.name}
          content-type: application/json
        input:
          destination: test-input
          group: ${spring.application.name}
          content-type: text/plain
        output:
          destination: test-output
          group: ${spring.application.name}
          content-type: text/plain

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:topsecret@localhost:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
hystrix:
  shareSecurityContext: true
  command.default.execution.isolation.thread.timeoutInMilliseconds: 600000 # 10 minutes
ribbon:
  ConnectTimeout: 300000 # 5 minutes
  ReadTimeout: 600000 # 10 minutes
 